### ISSUE TITLE
TypeError: arrangeData is not a function when using Node v23

### ISSUE THREAD

**Issue by cosmopetrich** [anvilco/spectaql#1001]
When using NodeJS v23.1.0 or v23.0.0, spectaql 3.0.2 will fail with `TypeError: arrangeData is not a function` even with a minimal config such as the example included in this repository.

```
$ node --version
v23.1.0
$ spectaql --config examples/config.yml 
TypeError: arrangeData is not a function
    at run (/usr/local/share/nvm/versions/node/v23.1.0/lib/node_modules/spectaql/dist/spectaql/index.js:105:17)
    at async run (/usr/local/share/nvm/versions/node/v23.1.0/lib/node_modules/spectaql/dist/index.js:339:59)
```

The same config seems to work fine when using LTS.

```
$ node --version
v22.10.0
$ spectaql --config examples/config.yml 
[...]
All tasks complete
```

**Comment by ecesar88** [comment]
Also getting this error on Node23

**Comment by pawel-zmarlak-pg** [comment]
Having the same issue on Node v23.7.0

**Comment by lukasulbing** [comment]
same issue here (Node v23.3.0 and spectaql 3.0.3)

**Comment by newhouse** [comment]
I haven't looked at it at all, but it sounds like it's isolated/new in Node 23. Does anyone here have any idea (before I look at it) why this is happening in Node 23 all of the sudden?  Some change that anyone's aware of?

**Comment by tdschwarz** [comment]
This appears to be related to the `default` option for `themeDir`. I see the same error when no `themeDir` argument is specified or `themeDir: default` is used, but do not see it when `basic` or `spectaql` are used for `themeDir`
