### ISSUE TITLE
Error: Task "compile-handlebars" not found

### ISSUE THREAD

**Issue by raweber42** [anvilco/spectaql#970]
We are new to spectaql and want to use it for our companies' documentation. I followed the step-by-step guide on the github main page, bug when running `npm run develop config.yaml` with our own configuration, I receive

```
[...]Running "connect:server" (connect) task
Error: Task "compile-handlebars" not found.
    at Task.run (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:172:28)
    at Object.thisTask.fn (/Users/test/spectaql/node_modules/grunt/lib/grunt/task.js:70:16)
    at Object.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:294:30)
    at Task.runTaskFn (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:244:24)
    at Task.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:293:12)
    at Task.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:223:9)
    at Task.runTaskFn (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:247:9)
    at Task.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:293:12)
    at Task.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:223:9)
    at Task.runTaskFn (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:247:9)
    at Task.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:293:12)
    at Task.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:223:9)
    at Task.runTaskFn (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:247:9)
    at Task.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:293:12)
    at Task.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:223:9)
    at Task.runTaskFn (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:247:9)
    at Task.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:293:12)
    at Task.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:223:9)
    at Task.runTaskFn (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:247:9)
    at Task.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:293:12)
    at Task.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:223:9)
    at Task.runTaskFn (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:247:9)
    at Task.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:293:12)
    at Task.<anonymous> (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:223:9)
    at Timeout._onTimeout (/Users/test/spectaql/node_modules/grunt/lib/util/task.js:234:33)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

[nodemon] app crashed - waiting for file changes before starting...
```

I don't see what could be the issue, I have updated my `node` version via `nvm`. 

Help much appreciated! :)

**Comment by newhouse** [comment]
Hi there @raweber42 and thanks for using SpectaQL!

This is a little bug that will be fixed once [this](https://github.com/anvilco/spectaql/pull/971) goes in. Until then, try executing `npm run clean-build:vendor` once, then your `npm run develop` command should work.

Side note: is there a reason that you're cloning the repo and using the `develop` approach vs using the `spectaql` npm package?

Closing this for now as there's a workaround for now, and a fix coming soon.
